name: WindowsBuild

on:
  push:
    branches:
    - develop

jobs:
  buildJob:
    runs-on: ubuntu-latest
    container: docker://gableroux/unity3d:${{ matrix.unity-tag }}
    strategy:
      matrix:
        unity-tag: [2018.4.9f1]

    steps:
    - uses: actions/checkout@master
    - run: echo "${LICENSE}" | tr -d '\r' > /opt/Unity/Editor/Unity_lic.ulf
      env:
        LICENSE: ${{ secrets.LICENSE }}
    - run: /opt/Unity/Editor/Unity -batchmode -nographics -logFile -projectPath . -executeMethod BuildCommand.Build -platform Windows -manualLicenseFile /opt/Unity/Editor/Unity_lic.ulf -devmode true
    - uses: actions/upload-artifact@master
      with:
        name: Builds
        path: path/to/artifact
