name: WindowsBuild

on:
  push:
    branches:
    - develop

jobs:
  buildJob:
    runs-on: ubuntu-latest
    container: docker://gableroux/unity3d:${{ matrix.unity-tag }}
    strategy:
      matrix:
        unity-tag: [2018.4.9f1]

    steps:
    - uses: actions/checkout@master
    - run: echo "${UNITY_LICENSE}" | tr -d '\r' > /root/.local/share/unity3d/Unity/Unity_lic.ulf
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
    - run: /opt/Unity/Editor/Unity -batchmode -nographics -silent-crashes -logFile -projectPath . -executeMethod BuildCommand.Build -platform Windows -manualLicenseFile ./Unity_v2018.x.ulf -devmode true
    - uses: actions/upload-artifact@master
      with:
        name: Builds
        path: path/to/artifact
