name: AndroidBuild

on:
  push:
    branches:
    - develop

jobs:
  buildJob:
    runs-on: ubuntu-latest
    container: docker://gableroux/unity3d:${{ matrix.unity-tag }}
    strategy:
      matrix:
        unity-tag: [2019.4.0f1-android]

    steps:
    - uses: actions/checkout@master
    - run: echo "${LICENSE}" | tr -d '\r' > /opt/Unity/Editor/Unity_lic.ulf
      env:
        LICENSE: ${{ secrets.LICENSE }}
    - run: ls -al
    - run: /opt/Unity/Editor/Unity -batchmode -logFile -nographics -manualLicenseFile /opt/Unity/Editor/Unity_lic.ulf || exit 0
    - run: /opt/Unity/Editor/Unity -batchmode -nographics -logFile -projectPath . -projectPath . -executeMethod BuildCommand.Build -platform Android -devmode true || exit 0
    - uses: actions/upload-artifact@master
      with:
        name: Builds
        path: Build
